application: modysseys
version: motorcycle
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /media
  static_dir: media

- url: /_media
  static_dir: kay/media

- url: /blank.html
  static_files: blog/templates/blank.html
  upload: blog/templates/blank.html

- url: /_kay/.*
  script: kay/main.py
  login: admin

- url: /_ah/queue/deferred
  script: kay/main.py
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /.*
  script: kay/main.py

skip_files: |
  ^(.*/)?(
  (_backup/.*)|
  (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (cron\.yaml)|
  (cron\.yml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*\.po)|
  (.*\.pot)|
  (\..*)|
  (app\.yaml\.sample)|
  (index\.yaml\.sample)|
  (cron\.yaml\.sample)|
  (manage\.py)|
  (^[^\/]+\/tests\.py$)|
  (^[^\/]+\/tests\/.*$)|
  (TODO)|
  (TODO\.pdf)|
  (README)|
  (README\.pdf)|
  (LICENSE)|
  (AUTHORS)|
  (RELEASE_NOTES)|
  (docs\/.*)|
  (kay\/management\/.*)|
  )$

